//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTKit/DVTLayoutView_ML.h>

@class NSView;

@interface _TtC19IDEMLKitModelEditor37MLKitViewerResizingCapsuleContentView : DVTLayoutView_ML
{
    // Error parsing type: , name: subViewInset
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutBottomUp;
- (void)awakeFromNib;
@property(nonatomic, readonly) NSView *onlySubview;
@property(nonatomic, readonly) CDStruct_d2b197d1 subViewInset; // @synthesize subViewInset;

@end

