//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDEGroup.h>

@class NSString;

@interface IDEGroup (IDEKit)
@property(nonatomic, readonly) NSString *ide_childItemsGroupIdentifier;
@end

