//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IBAttributeSearchLocation, IBMemberID, NSString;

@interface IBTextFragment : NSObject
{
    NSString *_text;
    IBMemberID *_memberID;
    IBAttributeSearchLocation *_attributeSearchLocation;
}

@property(readonly) IBAttributeSearchLocation *attributeSearchLocation; // @synthesize attributeSearchLocation=_attributeSearchLocation;
@property(readonly) IBMemberID *memberID; // @synthesize memberID=_memberID;
@property(readonly) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithMemberID:(id)arg1 attributeSearchLocation:(id)arg2 text:(id)arg3;

@end

