//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSCatalogColor.h>

@interface NSCatalogColor (IBICPrivate)
+ (id)ib_newWithCoder:(id)arg1 zone:(struct _NSZone *)arg2;
@end

