//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTSourceControlHostedAccount/_TtC29DVTSourceControlHostedAccount15ServicesContext.h>

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface _TtC29DVTSourceControlHostedAccount22GitHubListReposRequest : _TtC29DVTSourceControlHostedAccount15ServicesContext
{
}

- (id)initWithAccount:(id)arg1;
@property(nonatomic, readonly) long long resultsPerPage;
@property(nonatomic, readonly) NSDictionary *parameters;
@property(nonatomic, readonly) NSString *endpoint;

@end

