//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC29DVTSourceControlHostedAccount19GitHubAuthorization : NSObject
{
    // Error parsing type: , name: token
    // Error parsing type: , name: hashedToken
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *description;
@property(nonatomic, readonly) NSString *hashedToken; // @synthesize hashedToken;
@property(nonatomic, readonly) NSString *token; // @synthesize token;

@end

