//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTSourceControlHostedAccount/_TtC29DVTSourceControlHostedAccount15ServicesContext.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface _TtC29DVTSourceControlHostedAccount25GitHubOrganizationRequest : _TtC29DVTSourceControlHostedAccount15ServicesContext
{
    // Error parsing type: , name: organization
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithAccount:(id)arg1;
- (id)initWithAccount:(id)arg1 organization:(id)arg2;
@property(nonatomic, readonly) NSString *endpoint;
@property(nonatomic, readonly) NSString *organization; // @synthesize organization;

@end

