//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURLSession;

__attribute__((visibility("hidden")))
@interface _TtC29DVTSourceControlHostedAccount16ServicesExecutor : NSObject
{
    // Error parsing type: , name: session
    // Error parsing type: , name: dataTask
    // Error parsing type: , name: suppressAuthenticationFailure
    // Error parsing type: , name: context
    // Error parsing type: , name: isCancelled
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic) BOOL isCancelled; // @synthesize isCancelled;
- (void)cancel;
@property(nonatomic, retain) id context; // @synthesize context;
@property(nonatomic) BOOL suppressAuthenticationFailure; // @synthesize suppressAuthenticationFailure;
- (id)initWithSession:(id)arg1;
@property(nonatomic, readonly) NSURLSession *session; // @synthesize session;

@end

