//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;

@interface _TtC29DVTSourceControlHostedAccount22GitHubBareOrganization : NSObject
{
    // Error parsing type: , name: login
    // Error parsing type: , name: apiURL
    // Error parsing type: , name: avatarURL
    // Error parsing type: , name: desc
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *desc; // @synthesize desc;
@property(nonatomic, readonly) NSURL *avatarURL; // @synthesize avatarURL;
@property(nonatomic, readonly) NSURL *apiURL; // @synthesize apiURL;
@property(nonatomic, readonly) NSString *login; // @synthesize login;

@end

