//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC29DVTSourceControlHostedAccount17GitHubSingleError : NSObject
{
    // Error parsing type: , name: resource
    // Error parsing type: , name: code
    // Error parsing type: , name: field
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *field; // @synthesize field;
@property(nonatomic, readonly) NSString *resource; // @synthesize resource;

@end

