//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTSourceControlHostedAccount/_TtC29DVTSourceControlHostedAccount15ServicesContext.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface _TtC29DVTSourceControlHostedAccount17GitHubRepoRequest : _TtC29DVTSourceControlHostedAccount15ServicesContext
{
    // Error parsing type: , name: repo
    // Error parsing type: , name: owner
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithAccount:(id)arg1;
- (id)initWithAccount:(id)arg1 owner:(id)arg2 repo:(id)arg3;
@property(nonatomic, readonly) NSString *endpoint;
@property(nonatomic, readonly) NSString *owner; // @synthesize owner;
@property(nonatomic, readonly) NSString *repo; // @synthesize repo;

@end

