//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTSourceControlHostedAccount/_TtC29DVTSourceControlHostedAccount15ServicesContext.h>

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface _TtC29DVTSourceControlHostedAccount29GitHubCreateRepositoryRequest : _TtC29DVTSourceControlHostedAccount15ServicesContext
{
    // Error parsing type: , name: name
    // Error parsing type: , name: desc
    // Error parsing type: , name: homepage
    // Error parsing type: , name: private
    // Error parsing type: , name: org
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithAccount:(id)arg1;
- (id)initWithAccount:(id)arg1 name:(id)arg2 description:(id)arg3 homepage:(id)arg4 private:(BOOL)arg5 org:(id)arg6;
@property(nonatomic, readonly) NSDictionary *body;
@property(nonatomic, readonly) NSString *endpoint;

@end

