//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTSourceControlHostedAccount/_TtC29DVTSourceControlHostedAccount15ServicesContext.h>

@class NSString, _TtC29DVTSourceControlHostedAccount10GitHubRepo;

__attribute__((visibility("hidden")))
@interface _TtC29DVTSourceControlHostedAccount17GitHubStarRequest : _TtC29DVTSourceControlHostedAccount15ServicesContext
{
    // Error parsing type: , name: repo
    // Error parsing type: , name: starRequestType
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithAccount:(id)arg1;
@property(nonatomic, readonly) NSString *endpoint;
@property(nonatomic, retain) _TtC29DVTSourceControlHostedAccount10GitHubRepo *repo; // @synthesize repo;

@end

