//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTSourceControlHostedAccount/GitHubAccount.h>

@interface GitHubAccount (DVTSourceControlHostedAccount1)
- (id)urlFor:(id)arg1 revision:(id)arg2;
- (id)urlFor:(id)arg1 tag:(id)arg2;
- (id)urlFor:(id)arg1 branch:(id)arg2;
- (id)urlFor:(id)arg1;
@end

