//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface DVTCrashPointAppStoreSourceStore : NSObject
{
    NSMutableDictionary *_crashPointSources;
}

+ (id)defaultStore;
@property(retain, nonatomic) NSMutableDictionary *crashPointSources; // @synthesize crashPointSources=_crashPointSources;
- (void).cxx_destruct;
- (void)addCrashPointAppStoreSource:(id)arg1;
- (id)crashPointAppStoreSourceForAppIdentifier:(id)arg1 extensionPointIdentifier:(id)arg2;
- (id)init;

@end

