//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs40_SwiftNativeNSArrayWithContiguousStorage.h>

@interface _TtCs21_SwiftDeferredNSArray : _TtCs40_SwiftNativeNSArrayWithContiguousStorage
{
    // Error parsing type: , name: _heapBufferBridged_DoNotUse
    // Error parsing type: , name: _nativeStorage
}

- (id)init;
@property(nonatomic, readonly) long long count;

@end

