//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "__T013IDEFoundation28IDEDocumentationSearchResultCN.h"

@class NSImage;

@interface __T013IDEFoundation28IDEDocumentationSearchResultCN (IDEDocViewer)
@property(nonatomic, readonly) NSImage *ide_symbolIcon;
@end

