//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEDocViewer/_TtC12IDEDocViewer24IDEDocReferenceNavigator.h>

@class _TtC12IDEDocViewer24IDEDocumentationLanguage;

@interface _TtC12IDEDocViewer44IDEObjectiveCReferenceDocumentationNavigator : _TtC12IDEDocViewer24IDEDocReferenceNavigator
{
}

- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic, readonly) _TtC12IDEDocViewer24IDEDocumentationLanguage *documentationSection;

@end

