//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IDEActivityLogSection;

@interface _TtC17IDEXCBuildSupport31IDEActivityLogSectionCacheEntry : NSObject
{
    // Error parsing type: , name: logSection
    // Error parsing type: , name: subcaches
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)subcacheEntryWithSignature:(id)arg1;
- (id)initWithLogSection:(id)arg1;
@property(nonatomic, retain) IDEActivityLogSection *logSection; // @synthesize logSection;

@end

