//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "__T016DVTSourceControl0aB12RemoteBranchCN.h"

@class NSString;

@interface __T016DVTSourceControl0aB12RemoteBranchCN (IDESourceControlUI)
@property(nonatomic, readonly) NSString *inspectorExtensionIdentifier;
@end

