//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDESourceControlUI/_TtC18IDESourceControlUI23TrainyardViewController.h>

#import <IDESourceControlUI/DVTTextFindable-Protocol.h>

@interface _TtC18IDESourceControlUI23TrainyardViewController (IDESourceControlUI3) <DVTTextFindable>
- (id)findStringMatchingDescriptor:(id)arg1 backwards:(BOOL)arg2 from:(id)arg3 to:(id)arg4;
@end

