//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDESourceControlUI/DVTInvalidation-Protocol.h>

@protocol DVTSourceControlCancellable;

@interface _TtC18IDESourceControlUI35SourceControlInvalidatableOperation : NSObject <DVTInvalidation>
{
    // Error parsing type: , name: operation
    // Error parsing type: , name: isValid
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic) BOOL valid; // @synthesize valid=isValid;
- (BOOL)isValid;
- (void)invalidate;
- (void)primitiveInvalidate;
- (id)initWithOperation:(id)arg1;
@property(nonatomic, retain) id <DVTSourceControlCancellable> operation; // @synthesize operation;

@end

