//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTFoundation/DVTDocumentLocation.h>

@class DVTSourceControlVisualLogItem, _TtC18IDESourceControlUI25WorkingCopyEditorDocument;

@interface _TtC18IDESourceControlUI32SourceControlLogDocumentLocation : DVTDocumentLocation
{
    // Error parsing type: , name: logItem
    // Error parsing type: , name: workingCopyDocument
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithDocumentURL:(id)arg1 timestamp:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)initWithLogItem:(id)arg1 workingCopyDocument:(id)arg2;
@property(nonatomic, readonly) _TtC18IDESourceControlUI25WorkingCopyEditorDocument *workingCopyDocument; // @synthesize workingCopyDocument;
@property(nonatomic, readonly) DVTSourceControlVisualLogItem *logItem; // @synthesize logItem;

@end

