//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDESourceControlUI/_TtC18IDESourceControlUI24SourceControlGroupHolder.h>

@class DVTFileDataType, DVTSourceControlRemoteRepository, DVTSourceControlWorkingCopy, NSImage, NSString;

@interface _TtC18IDESourceControlUI22RemoteRepositoryHolder : _TtC18IDESourceControlUI24SourceControlGroupHolder
{
    // Error parsing type: , name: remote
    // Error parsing type: , name: workingCopy
}

- (CDUnknownBlockType).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
@property(nonatomic, readonly) NSString *navigableItem_toolTip;
- (BOOL)isEqualTo:(id)arg1;
@property(nonatomic, readonly) NSString *navigableItem_name;
@property(nonatomic, readonly) BOOL navigableItem_isLeaf;
@property(nonatomic, readonly) NSImage *navigableItem_image;
@property(nonatomic, readonly) DVTFileDataType *navigableItem_documentType;
- (id)ideModelObjectTypeIdentifier;
- (id)initWithName:(id)arg1 remote:(id)arg2 identifier:(id)arg3 workingCopy:(id)arg4;
@property(nonatomic, retain) DVTSourceControlWorkingCopy *workingCopy; // @synthesize workingCopy;
@property(nonatomic, retain) DVTSourceControlRemoteRepository *remote; // @synthesize remote;

@end

