//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTextField.h>

@interface _TtC18IDESourceControlUI37SourceControlPushPullCountStatusField : NSTextField
{
    // Error parsing type: , name: count
    // Error parsing type: , name: type
}

+ (Class)cellClass;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setup;
- (id)stringFor:(long long)arg1;
@property(nonatomic) long long count; // @synthesize count;

@end

