//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC18IDESourceControlUI24SourceControlSearchToken : NSObject
{
    // Error parsing type: , name: searchString
    // Error parsing type: , name: type
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithSearchString:(id)arg1;
@property(nonatomic, readonly) NSString *serializationString;
@property(nonatomic, copy) NSString *searchString; // @synthesize searchString;

@end

