//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDESourceControlUI/_TtC18IDESourceControlUI23TrainyardViewController.h>

#import <IDESourceControlUI/DVTTableViewDelegate-Protocol.h>

@interface _TtC18IDESourceControlUI23TrainyardViewController (IDESourceControlUI2) <DVTTableViewDelegate>
- (BOOL)tableView:(id)arg1 doCommandBySelector:(SEL)arg2;
@end

