//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSArray, NSStackView;

@interface _TtC18IDESourceControlUI23ExtraTagsViewController : NSViewController
{
    // Error parsing type: , name: stackView
    // Error parsing type: , name: labelFields
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic, copy) NSArray *labelFields; // @synthesize labelFields;
@property(nonatomic) __weak NSStackView *stackView; // @synthesize stackView;

@end

