//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSTextField;

@interface GPUTraceNoDataViewController : NSViewController
{
    NSTextField *_text;
}

@property __weak NSTextField *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (void)viewDidLoad;

@end

