//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC7XCBuild31XCBBuildOperationDiagnosticInfo : NSObject
{
    // Error parsing type: , name: path
    // Error parsing type: , name: line
    // Error parsing type: , name: column
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) long long column; // @synthesize column;
@property(nonatomic, readonly) long long line; // @synthesize line;
@property(nonatomic, readonly) NSString *path; // @synthesize path;

@end

