//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface _TtC7XCBuild16XCBSettingsTable : NSObject
{
    // Error parsing type: , name: table
}

- (CDUnknownBlockType).cxx_destruct;
- (void)setValue:(id)arg1 forMacro:(id)arg2;
- (id)init;
@property(nonatomic, copy) NSDictionary *table; // @synthesize table;

@end

