//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC7XCBuild23XCBMacroEvaluationScope : NSObject
{
    // Error parsing type: , name: session
    // Error parsing type: , name: settingsHandle
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)evaluateMacroAsString:(id)arg1 overrides:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)evaluateMacroAsStringList:(id)arg1 overrides:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)evaluateMacroStringListExpression:(id)arg1 overrides:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)evaluateMacroStringExpressionAsStringList:(id)arg1 overrides:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)evaluateMacroStringExpressionArray:(id)arg1 overrides:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)evaluateMacroAsBool:(id)arg1 overrides:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)evaluateMacroStringExpression:(id)arg1 overrides:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)init:(id)arg1:(id)arg2;
@property(nonatomic, readonly) NSString *settingsHandle; // @synthesize settingsHandle;

@end

