//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEQuickHelp/IDEQuickHelpQueryResult.h>

@class NSString, _TtC16DVTDocumentation24DVTDocumentationResponse;

@interface _TtC12IDEQuickHelp26IDEQuickHelpQueryDNTResult : IDEQuickHelpQueryResult
{
    // Error parsing type: , name: response
    // Error parsing type: , name: alternateDescription
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) long long hash;
- (BOOL)isEqual:(id)arg1;
- (void)reportToMessageTracer;
@property(nonatomic, readonly) NSString *abstract;
- (id)initWithAlternateDescription:(id)arg1;
- (id)initWithResponse:(id)arg1;
@property(nonatomic, copy) NSString *alternateDescription; // @synthesize alternateDescription;
@property(nonatomic, retain) _TtC16DVTDocumentation24DVTDocumentationResponse *response; // @synthesize response;

@end

