//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XCTDaemonControl/NSObject-Protocol.h>

@class NSError;

@protocol XCTDaemonRequest <NSObject>
- (void)handleConnectionFailure:(NSError *)arg1;
- (void)sendToDaemonProxy:(id)arg1;
@end

