//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface _XCSLocalService_ItemsByWorkspacesCache : NSObject
{
    NSArray *_botIdentifiersMatching;
    NSArray *_botIdentifiersNotMatching;
}

@property(copy, nonatomic) NSArray *botIdentifiersNotMatching; // @synthesize botIdentifiersNotMatching=_botIdentifiersNotMatching;
@property(copy, nonatomic) NSArray *botIdentifiersMatching; // @synthesize botIdentifiersMatching=_botIdentifiersMatching;
- (void).cxx_destruct;

@end

