//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XCSUI/XCSBotSupportingEditor.h>

@class DVTObservingToken, IDETestReportTestRunFetcher, NSDictionary, XCSCodeCoverageIntegration;

@interface XCSBotIntegrationEditor : XCSBotSupportingEditor
{
    DVTObservingToken *_botObserver;
    DVTObservingToken *_integrationObserver;
    IDETestReportTestRunFetcher *_testRunFetcher;
    XCSCodeCoverageIntegration *_cachedCodeCoverage;
    NSDictionary *_testKeyPathsAndTests;
}

@property(retain, nonatomic) NSDictionary *testKeyPathsAndTests; // @synthesize testKeyPathsAndTests=_testKeyPathsAndTests;
- (void).cxx_destruct;
- (void)coverageReportData:(CDUnknownBlockType)arg1;
- (void)testReportData:(CDUnknownBlockType)arg1;
- (void)showLogsTab:(id)arg1;
- (id)integrationInProgressChoices;
- (id)choices;
- (void)selectDocumentLocations:(id)arg1;
- (id)cachedChoiceWithTitle:(id)arg1;
- (void)primitiveInvalidate;
- (void)viewDidInstall;
- (void)loadView;

@end

