//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSURL;

@interface XCSUIXPCRequest : NSObject
{
    // Error parsing type: , name: xcodeUrl
    // Error parsing type: , name: authData
}

+ (BOOL)supportsSecureCoding;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithXcode:(id)arg1 authData:(id)arg2;
@property(nonatomic, readonly) NSData *authData; // @synthesize authData;
@property(nonatomic, readonly) NSURL *xcodeUrl; // @synthesize xcodeUrl;

@end

