//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "XCSourceEditorExtension-Protocol.h"

@interface _TtC22XcodeBuiltInExtensions21SourceEditorExtension : NSObject <XCSourceEditorExtension>
{
}

- (id)init;
- (void)extensionDidFinishLaunching;

@end

