//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTFoundation/DVTProvisioningProfileProvider.h>

@interface DVTProvisioningProfileProvider (IDEAdditions)
- (id)basicTeamFromProfile:(id)arg1;
- (BOOL)isAutomaticProvisioningDevelopmentProfile:(id)arg1;
@end

