//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class IDEBreakpoint, NSArray;

@protocol IDEBreakpointDelegate

@optional
- (void)breakpointLocationsAdded:(NSArray *)arg1 removed:(NSArray *)arg2;
- (BOOL)breakpointShouldBeActivated:(IDEBreakpoint *)arg1;
- (void)breakpointEnablementChanged:(IDEBreakpoint *)arg1;
@end

