//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTKit/_TtC6DVTKit16DVTIconGenerator.h>

@class NSURL;

__attribute__((visibility("hidden")))
@interface _TtC6DVTKit28DVTIconFromFileSpecGenerator : _TtC6DVTKit16DVTIconGenerator
{
    // Error parsing type: , name: bundleURL
    // Error parsing type: , name: specFileURL
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, readonly) NSURL *specFileURL; // @synthesize specFileURL;
@property(nonatomic, readonly) NSURL *bundleURL; // @synthesize bundleURL;

@end

