//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC6DVTKit16DVTIconGenerator : NSObject
{
    // Error parsing type: , name: identifier
    // Error parsing type: , name: iconSpec
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)generateIconWithSize:(double)arg1;
@property(nonatomic, readonly) NSString *identifier; // @synthesize identifier;

@end

