//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface _TtC23DNTDocumentationSupportP33_6F5DDAB829CC5015B48EAF8B71D6F28814IndexOperation : NSOperation
{
    // Error parsing type: , name: documentationService
    // Error parsing type: , name: index
    // Error parsing type: , name: dataRange
    // Error parsing type: , name: replacementWords
    // Error parsing type: , name: errorHandler
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)main;
@property(nonatomic, readonly) CDUnknownBlockType errorHandler; // @synthesize errorHandler;
@property(nonatomic, readonly) NSDictionary *replacementWords; // @synthesize replacementWords;

@end

