//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class NSProgressIndicator;

__attribute__((visibility("hidden")))
@interface _TtC12SourceEditor30ActionMenuLoadingTableCellView : NSTableCellView
{
    // Error parsing type: , name: progressIndicator
    // Error parsing type: , name: isDark
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) BOOL isDark; // @synthesize isDark;
- (void)awakeFromNib;
@property(nonatomic, retain) NSProgressIndicator *progressIndicator; // @synthesize progressIndicator;

@end

