//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC12SourceEditorP33_452FC792F9E02464CCF1D8C302F2688825TextualUndoStackOperation : SwiftObject
{
    // Error parsing type: , name: actionName
    // Error parsing type: , name: representedOperationCount
    // Error parsing type: , name: type
    // Error parsing type: , name: range
    // Error parsing type: , name: text
    // Error parsing type: , name: dataSource
}

@end

