//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC12SourceEditor17FoldingController : SwiftObject
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: dataSourceObserver
    // Error parsing type: , name: dataSource
    // Error parsing type: , name: allFolds
    // Error parsing type: , name: lowWaterMarkPosition
    // Error parsing type: , name: highWaterMarkPosition
}

@end

