//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

__attribute__((visibility("hidden")))
@interface _TtC12SourceEditor26ElidedLineSubstitutionView : NSView
{
    // Error parsing type: , name: shouldDrawDivider
}

- (id)initWithFrame:(struct CGRect)arg1;
- (struct CGSize)preferredSizeWithConstrainedBy:(struct CGSize)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
@property(nonatomic) BOOL shouldDrawDivider; // @synthesize shouldDrawDivider;

@end

