//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SourceEditor/_TtC12SourceEditorP33_452FC792F9E02464CCF1D8C302F2688825TextualUndoStackOperation.h>

@interface _TtC12SourceEditorP33_452FC792F9E02464CCF1D8C302F2688833CoalescedTexualUndoStackOperation : _TtC12SourceEditorP33_452FC792F9E02464CCF1D8C302F2688825TextualUndoStackOperation
{
}

@end

