//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SourceEditor/_TtC12SourceEditor34SourceEditorLineAnnotationDropdown.h>

@interface _TtC12SourceEditor34SourceEditorLineAnnotationDropdown (SourceEditor3)
- (void)calculateLayoutInfo;
@end

