//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC12SourceEditor27StructuredEditingController : SwiftObject
{
    // Error parsing type: , name: dataSource
    // Error parsing type: , name: structuredEditingDelegate
    // Error parsing type: , name: transientSelectionContext
    // Error parsing type: , name: selectionContext
    // Error parsing type: , name: selectionDisplay
    // Error parsing type: , name: actionType
    // Error parsing type: , name: isDoubleClickTimerOn
    // Error parsing type: , name: delayedUpdateSelectionContextAction
    // Error parsing type: , name: keyBindingMonitor
}

@end

