//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSAccessibilityElement.h>

__attribute__((visibility("hidden")))
@interface _TtC12SourceEditorP33_3253A97ADC8443EA56C86E7438CE051B23AnnotationAccessibility : NSAccessibilityElement
{
    // Error parsing type: , name: annotation
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (BOOL)accessibilityPerformPress;
- (id)accessibilityLabel;
- (id)accessibilityRole;
- (BOOL)isAccessibilityElement;

@end

