//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSColor, NSLayoutConstraint;

__attribute__((visibility("hidden")))
@interface _TtC12SourceEditorP33_5B634B9DCDB55D6100C0DC388A389C2744SourceEditorLineAnnotationDropdownBackground : NSView
{
    // Error parsing type: , name: topConstraint
    // Error parsing type: , name: heightConstraint
    // Error parsing type: , name: backgroundColor
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, retain) NSColor *backgroundColor; // @synthesize backgroundColor;
- (void)viewDidChangeBackingProperties;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) NSLayoutConstraint *heightConstraint; // @synthesize heightConstraint;
@property(nonatomic, retain) NSLayoutConstraint *topConstraint; // @synthesize topConstraint;

@end

