//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSAccessibilityElement.h>

@class _TtC12SourceEditor16SourceEditorView;

__attribute__((visibility("hidden")))
@interface _TtC12SourceEditor29AnnotationsAccessibilityGroup : NSAccessibilityElement
{
    // Error parsing type: , name: sourceEditorView
    // Error parsing type: , name: annotations
    // Error parsing type: , name: needAnnotationAccessibilityUpdate
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)accessibilityChildren;
- (id)accessibilityLabel;
- (id)accessibilityIdentifier;
- (id)accessibilityRole;
- (BOOL)isAccessibilityElement;
- (void)setNeedsAnnotationAccessibilityUpdate;
- (id)initWithSourceEditorView:(id)arg1;
@property(nonatomic) __weak _TtC12SourceEditor16SourceEditorView *sourceEditorView; // @synthesize sourceEditorView;

@end

