//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SourceEditor/_TtC12SourceEditor28SourceEditorGutterMarginView.h>

@class NSDictionary, NSFont;

__attribute__((visibility("hidden")))
@interface _TtC12SourceEditor35SourceEditorGutterMarginContentView : _TtC12SourceEditor28SourceEditorGutterMarginView
{
    // Error parsing type: , name: requiredWidth
    // Error parsing type: , name: lineNumberLayers
    // Error parsing type: , name: reusableLineNumberLayers
    // Error parsing type: , name: lastLineNumberRange
    // Error parsing type: , name: lineNumbersEnabled
    // Error parsing type: , name: lineNumberFont
    // Error parsing type: , name: layerSizeCache
    // Error parsing type: , name: annotations
    // Error parsing type: , name: lineIdentifierOrderedAnnotations
    // Error parsing type: , name: interaction
    // Error parsing type: , name: hoveringAnnotation
    // Error parsing type: , name: layoutIntentMap
}

- (CDUnknownBlockType).cxx_destruct;
- (void)removeAllAnnotations;
- (void)removeLineNumberLayerFor:(long long)arg1;
- (id)dequeOrCreateNewTextLayerFor:(long long)arg1;
@property(nonatomic, retain) NSFont *lineNumberFont; // @synthesize lineNumberFont;
@property(nonatomic, copy) NSDictionary *reusableLineNumberLayers; // @synthesize reusableLineNumberLayers;
@property(nonatomic, copy) NSDictionary *lineNumberLayers; // @synthesize lineNumberLayers;
- (BOOL)isFlipped;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(nonatomic, readonly) BOOL flipped;

@end

