//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SourceEditor/_TtC12SourceEditor27TextFindPanelViewController.h>

#import <SourceEditor/TextFindPatternPanel-Protocol.h>

@interface _TtC12SourceEditor27TextFindPanelViewController (SourceEditor1) <TextFindPatternPanel>
- (id)replacePatternField;
- (id)findPatternField;
@end

