//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSImage.h>

@interface NSImage (SourceEditor)
- (id)initWithNamed:(id)arg1 in:(id)arg2 compatibleWith:(id)arg3;
@end

