//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XCSAdministration/_TtC17XCSAdministration20AdministrationRecipe.h>

@class XCSSettings;

@interface _TtC17XCSAdministration17GetSettingsRecipe : _TtC17XCSAdministration20AdministrationRecipe
{
    // Error parsing type: , name: fetchSettingsOperation
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) XCSSettings *settings;
- (void)plan;

@end

