//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XCSAdministration/_TtC17XCSAdministration20AdministrationRecipe.h>

@class _TtC17XCSAdministration14NewUserAccount;

@interface _TtC17XCSAdministration21CreateBuildUserRecipe : _TtC17XCSAdministration20AdministrationRecipe
{
    // Error parsing type: , name: userToCreate
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)plan;
- (id)initWithUserToCreate:(id)arg1;
@property(nonatomic, readonly) _TtC17XCSAdministration14NewUserAccount *userToCreate; // @synthesize userToCreate;

@end

