//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface _TtC17XCSAdministration20AdministrationRecipe : NSObject
{
    // Error parsing type: , name: operations
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, copy) NSArray *operations; // @synthesize operations;
@property(nonatomic, readonly) BOOL isAppleInternal;
- (void)prepareOperation:(id)arg1 runner:(id)arg2;
- (void)plan;
- (void)enqueueOn:(id)arg1 runner:(id)arg2;

@end

