//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XCSAdministration/_TtC17XCSAdministration20AdministrationRecipe.h>

@class NSString, XCSService;

@interface _TtC17XCSAdministration14JoinTeamRecipe : _TtC17XCSAdministration20AdministrationRecipe
{
    // Error parsing type: , name: teamID
    // Error parsing type: , name: service
    // Error parsing type: , name: credentials
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)prepareOperation:(id)arg1 runner:(id)arg2;
- (void)plan;
- (id)initWithTeamID:(id)arg1 account:(id)arg2 service:(id)arg3;
- (id)initWithTeamID:(id)arg1 appleID:(id)arg2 password:(id)arg3;
@property(nonatomic, readonly) XCSService *service; // @synthesize service;
@property(nonatomic, readonly) NSString *teamID; // @synthesize teamID;

@end

