//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "__T012SourceEditor0aB4ViewCN.h"

#import <IDEPegasusSourceEditor/DVTFindPatternManager-Protocol.h>

@interface __T012SourceEditor0aB4ViewCN (IDEPegasusSourceEditor1) <DVTFindPatternManager>
- (BOOL)supportsPatterns;
- (id)replaceFieldForField:(id)arg1;
- (id)findFieldForField:(id)arg1;
@end

