//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "__T018SourceModelSupport0aB15LanguageServiceCN.h"

@interface __T018SourceModelSupport0aB15LanguageServiceCN (IDEPegasusSourceEditor)
- (void)willPassCodeCompletionContextToStrategies:(id)arg1 from:(id)arg2 wordStartLocation:(unsigned long long)arg3 string:(id)arg4 language:(id)arg5;
@end

