//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC22IDEPegasusSourceEditor24CrossLanguageRenameRules : SwiftObject
{
    // Error parsing type: , name: documentProvider
    // Error parsing type: , name: documentRelease
    // Error parsing type: , name: bestLocation
    // Error parsing type: , name: bestLocationDocument
}

@end

