//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEPegasusSourceEditor/_TtC22IDEPegasusSourceEditor29QuickHelpForceTouchController.h>

#import <IDEPegasusSourceEditor/NSImmediateActionAnimationController-Protocol.h>

@interface _TtC22IDEPegasusSourceEditor29QuickHelpForceTouchController (IDEPegasusSourceEditor) <NSImmediateActionAnimationController>
- (void)immediateActionRecognizerDidDismissAnimation:(id)arg1;
- (void)immediateActionRecognizerDidCompleteAnimation:(id)arg1;
- (void)immediateActionRecognizerDidCancelAnimation:(id)arg1;
- (void)immediateActionRecognizerDidUpdateAnimation:(id)arg1;
- (void)immediateActionRecognizerWillBeginAnimation:(id)arg1;
@end

