//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "__T012SourceEditor20ActionMenuControllerCN.h"

@interface _TtC22IDEPegasusSourceEditor39StructuredSelectionActionMenuController : __T012SourceEditor20ActionMenuControllerCN
{
    // Error parsing type: , name: range
    // Error parsing type: , name: context
    // Error parsing type: , name: nameRange
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;

@end

