//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEIndexGeniusResult.h>

@class DVTDocumentLocation;

__attribute__((visibility("hidden")))
@interface _TtC22IDEPegasusSourceEditorP33_25CE0C9BBF1DA229A87429291B73472131SourceCodeTestClassGeniusResult : IDEIndexGeniusResult
{
}

- (id)init;
- (id)initWithIndexSymbol:(id)arg1;
@property(nonatomic, readonly) DVTDocumentLocation *navigableItem_contentDocumentLocation;

@end

