//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC22IDEPegasusSourceEditor19RefactoringDelegate : SwiftObject
{
    // Error parsing type: , name: queue
    // Error parsing type: , name: sem
    // Error parsing type: , name: results
    // Error parsing type: , name: renameLocations
}

- (void)unhandledURL:(id)arg1 symbols:(id)arg2;
- (void)renameRangesFound:(id)arg1;
- (void)fileChanged:(id)arg1;
- (void)started;
- (void)finished;

@end

