//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

#import <IDEPegasusSourceEditor/IDEComparisonEditorScrollerAreaView-Protocol.h>

@class _TtC22IDEPegasusSourceEditor16SourceCodeEditor;

@interface _TtC22IDEPegasusSourceEditor29SourceCodeEditorContainerView : NSView <IDEComparisonEditorScrollerAreaView>
{
    // Error parsing type: , name: editor
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) NSView *viewToInstallScrollerIn;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 editor:(id)arg2;
@property(nonatomic) __weak _TtC22IDEPegasusSourceEditor16SourceCodeEditor *editor; // @synthesize editor;

@end

