//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEPegasusSourceEditor/_TtC22IDEPegasusSourceEditor18SourceCodeDocument.h>

@interface _TtC22IDEPegasusSourceEditor41IDEVersionEditorPrivateSourceCodeDocument : _TtC22IDEPegasusSourceEditor18SourceCodeDocument
{
}

- (id)init;

@end

