//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@class DVTTextAnnotation;

__attribute__((visibility("hidden")))
@interface _TtC22IDEPegasusSourceEditorP33_67A9D6685000B0232D92185A369E5C1219TextAnnotationLayer : CALayer
{
    // Error parsing type: , name: annotation
}

+ (id)defaultActionForKey:(id)arg1;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithLayer:(id)arg1;
- (id)init;
- (void)display;
- (struct CGSize)preferredFrameSize;
- (id)initWithCoder:(id)arg1;
- (id)initWithAnnotation:(id)arg1;
@property(nonatomic) __weak DVTTextAnnotation *annotation; // @synthesize annotation;

@end

