//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTKit/DVTControllerContentView.h>

@interface _TtC22IDEPegasusSourceEditor37AutoLayoutSyncedControllerContentView : DVTControllerContentView
{
    // Error parsing type: , name: didInitalize
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)didCompleteLayout;

@end

