//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEPegasusSourceEditor/CALayerDelegate-Protocol.h>

@class NSArray;

@interface _TtC22IDEPegasusSourceEditor31StaticAnalyzerStepVisualization : NSObject <CALayerDelegate>
{
    // Error parsing type: , name: visualization
    // Error parsing type: , name: stepLayers
    // Error parsing type: , name: hitTestViews
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)refreshInContentView:(id)arg1;
@property(nonatomic, readonly) NSArray *hitTestViews; // @synthesize hitTestViews;
- (void)didLayoutInContentView:(id)arg1;
- (void)willLayoutInContentView:(id)arg1;
- (id)init:(id)arg1;

@end

