//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTFoundation/DVTDiffLineDataSource.h>

@interface _TtC22IDEPegasusSourceEditor24SourceCodeDiffDataSource : DVTDiffLineDataSource
{
    // Error parsing type: , name: dataSourceObserver
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)dealloc;
- (id)arrangedContent;
- (id)initWithContent:(id)arg1;

@end

