//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEPegasusSourceEditor/_TtC22IDEPegasusSourceEditor16SourceCodeEditor.h>

#import <IDEPegasusSourceEditor/IDESourceControlBlameForLineEditorDataSource-Protocol.h>

@class NSView;

@interface _TtC22IDEPegasusSourceEditor16SourceCodeEditor (IDEPegasusSourceEditor) <IDESourceControlBlameForLineEditorDataSource>
- (struct CGRect)boundsForLineRange:(struct _NSRange)arg1;
@property(nonatomic, readonly) NSView *blameForLineView;
@property(nonatomic, readonly) struct _NSRange selectedLineRange;
@end

