//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEPegasusSourceEditor/_TtC22IDEPegasusSourceEditor18SourceCodeDocument.h>

#import <IDEPegasusSourceEditor/DVTTextDocumentLocationCharacterRangeConverter-Protocol.h>

@interface _TtC22IDEPegasusSourceEditor18SourceCodeDocument (IDEPegasusSourceEditor1) <DVTTextDocumentLocationCharacterRangeConverter>
- (id)documentLocationFromCharacterRange:(struct _NSRange)arg1;
- (struct _NSRange)characterRangeFromDocumentLocation:(id)arg1;
@end

