//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, _TtC22IDEPegasusSourceEditor16SourceCodeEditor;

@interface _TtC22IDEPegasusSourceEditor21RefactoringController : NSObject
{
    // Error parsing type: , name: gotAFailure
    // Error parsing type: , name: editor
    // Error parsing type: , name: updateTimer
    // Error parsing type: , name: changeCount
    // Error parsing type: , name: lastRefactoringRange
    // Error parsing type: , name: lastAvailableRefactorings
    // Error parsing type: , name: renameOperation
}

- (CDUnknownBlockType).cxx_destruct;
- (void)renameWithCodeRoll;
- (void)simpleRenameRefactor:(id)arg1;
- (void)selectionChanged;
- (void)indexChanged;
@property(nonatomic, copy) NSArray *lastAvailableRefactorings; // @synthesize lastAvailableRefactorings;
- (id)init;
@property(nonatomic) __weak _TtC22IDEPegasusSourceEditor16SourceCodeEditor *editor; // @synthesize editor;
- (void)reportError:(id)arg1;

@end

