//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEPegasusSourceEditor/_TtC22IDEPegasusSourceEditor17RefactoringResult.h>

@class NSString;

@interface _TtC22IDEPegasusSourceEditor23RefactoringRenameResult : _TtC22IDEPegasusSourceEditor17RefactoringResult
{
    // Error parsing type: , name: kind
    // Error parsing type: , name: argIndex
    // Error parsing type: , name: originalText
    // Error parsing type: , name: managedRange
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWith:(id)arg1 replacement:(id)arg2;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, copy) NSString *originalText; // @synthesize originalText;
@property(nonatomic) unsigned long long kind; // @synthesize kind;

@end

