//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEPegasusSourceEditor/_TtC22IDEPegasusSourceEditor20SourceCodeEditorView.h>

#import <IDEPegasusSourceEditor/DVTLineRangeCharacterRangeConverter-Protocol.h>

@interface _TtC22IDEPegasusSourceEditor20SourceCodeEditorView (IDEPegasusSourceEditor2) <DVTLineRangeCharacterRangeConverter>
- (struct _NSRange)lineRangeForCharacterRange:(struct _NSRange)arg1;
- (struct _NSRange)characterRangeForLineRange:(struct _NSRange)arg1;
@end

