//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC22IDEPegasusSourceEditorP33_1FF747B2AB42EBC82BFFF96A6B15EC6E42SourceCodeDocumentLanguageServiceExtension : SwiftObject
{
    // Error parsing type: , name: document
    // Error parsing type: , name: nodeAdjustRequests
    // Error parsing type: , name: allowIndexBasedSemanticColoring
}

@end

