//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEPegasusSourceEditor/_TtC22IDEPegasusSourceEditor20SourceCodeEditorView.h>

@interface _TtC22IDEPegasusSourceEditor24CodeRollSourceEditorView : _TtC22IDEPegasusSourceEditor20SourceCodeEditorView
{
    // Error parsing type: , name: setUpComplete
}

- (id)initWithCoder:(id)arg1 sourceEditorScrollViewClass:(Class)arg2;
- (id)initWithFrame:(struct CGRect)arg1 sourceEditorScrollViewClass:(Class)arg2;
- (void)resetCursorRects;
- (void)redo:(id)arg1;
- (void)undo:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)setupStructuredEditingController;
@property(nonatomic, readonly) BOOL acceptsFirstResponder;
- (void)changeToStandardEditor:(id)arg1;
- (void)insertBacktab:(id)arg1;
- (void)insertTab:(id)arg1;
- (void)keyDown:(id)arg1;
@property(nonatomic) BOOL setUpComplete; // @synthesize setUpComplete;

@end

