//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "__T09DVTMarkup20PlaygroundMarkupViewCN.h"

@interface _TtC22IDEPegasusSourceEditor20SourceCodeMarkupView : __T09DVTMarkup20PlaygroundMarkupViewCN
{
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (struct CGSize)preferredSizeWithConstrainedBy:(struct CGSize)arg1;

@end

