//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC22IDEPegasusSourceEditor11LanguageSet : SwiftObject
{
    // Error parsing type: , name: potentiallyUnsortedLanguages
    // Error parsing type: , name: languagesAreSorted
    // Error parsing type: , name: swift
    // Error parsing type: , name: markup
}

@end

