//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTObservingToken, IDEWorkspace, NSArray, NSString, _TtC22IDEPegasusSourceEditor23CodeRollNavItemProvider;

@interface _TtC22IDEPegasusSourceEditor19CodeRollNavItemRoot : NSObject
{
    // Error parsing type: , name: workspace
    // Error parsing type: , name: parent
    // Error parsing type: , name: workspaceObserver
    // Error parsing type: , name: codeRollNavItems
}

+ (id)keyPathsForValuesAffectingNavigableItem_childRepresentedObjects;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSArray *navigableItem_childRepresentedObjects;
- (void)removeNavItemsWithUrl:(id)arg1;
- (id)findOrCreateNavItemWithUrl:(id)arg1;
- (id)findNavItemWithUrl:(id)arg1;
- (id)initWithWorkspace:(id)arg1 parent:(id)arg2;
@property(nonatomic, readonly) NSString *navigableItem_name;
@property(nonatomic, copy) NSArray *codeRollNavItems; // @synthesize codeRollNavItems;
@property(nonatomic, retain) DVTObservingToken *workspaceObserver; // @synthesize workspaceObserver;
@property(nonatomic) __weak _TtC22IDEPegasusSourceEditor23CodeRollNavItemProvider *parent; // @synthesize parent;
@property(nonatomic) __weak IDEWorkspace *workspace; // @synthesize workspace;

@end

