//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC22IDEPegasusSourceEditorP33_E13EC967AEAED6426DEF531A62CCCA9C40PathTokenVisualizationDataSourceObserver : SwiftObject
{
    // Error parsing type: , name: pathTokenVisualization
    // Error parsing type: , name: observedDataSource
}

@end

