//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTFoundation/DVTDocumentLocation.h>

@class NSURL;

@interface _TtC22IDEPegasusSourceEditor24CodeRollDocumentLocation : DVTDocumentLocation
{
    // Error parsing type: , name: url
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithDocumentURL:(id)arg1 timestamp:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithCodeRollURL:(id)arg1 fileURL:(id)arg2;
@property(nonatomic, readonly) NSURL *url; // @synthesize url;

@end

