//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEPegasusSourceEditor/_TtC22IDEPegasusSourceEditor20SourceCodeEditorView.h>

#import <IDEPegasusSourceEditor/DVTSourceModelProvider-Protocol.h>

@interface _TtC22IDEPegasusSourceEditor20SourceCodeEditorView (IDEPegasusSourceEditor) <DVTSourceModelProvider>
- (id)sourceModel;
@end

