//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTKit/DVTAnnotationProvider.h>

@interface _TtC22IDEPegasusSourceEditor39SourceCodeEditorLocalAnnotationProvider : DVTAnnotationProvider
{
    // Error parsing type: , name: editor
}

+ (id)annotationProviderForContext:(id)arg1 error:(id *)arg2;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithEditor:(id)arg1;

@end

