//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEPegasusSourceEditor/DVTCharacterRangeFrameConverter-Protocol.h>
#import <IDEPegasusSourceEditor/DVTLineRangeCharacterRangeConverter-Protocol.h>
#import <IDEPegasusSourceEditor/DVTSourceCodeLanguageEditorView-Protocol.h>
#import <IDEPegasusSourceEditor/DVTSourceLandmarkItemContainer-Protocol.h>
#import <IDEPegasusSourceEditor/DVTSourceModelProvider-Protocol.h>
#import <IDEPegasusSourceEditor/DVTTextInsertionPointLocator-Protocol.h>

@protocol DVTSourceEditorView <DVTLineRangeCharacterRangeConverter, DVTSourceModelProvider, DVTCharacterRangeFrameConverter, DVTSourceCodeLanguageEditorView, DVTSourceLandmarkItemContainer, DVTTextInsertionPointLocator>
@end

