//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSAttributedString.h>

@class NSString;

@interface NSAttributedString (IDEPegasusSourceEditor)
@property(nonatomic, readonly) BOOL isImplicitRegularExpression;
@property(nonatomic, readonly) NSString *asTextFindString;
@end

